# Generated by Django 4.2.7 on 2025-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='economic_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='flexible_price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='travel_class',
            field=models.CharField(choices=[('economic', 'Economic'), ('flexible', 'Flexible')], default='economic', max_length=20),
        ),
    ]
